safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:     /jekyll_demo
url:         http://huangxc.com

source:      .
destination: ./_site
plugins:     ./_plugins

exclude:    [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".html"]
future:      true
lsi:         false
pygments:    true
markdown:    maruku

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids:    true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

permalink:    /:title

title:        narsi的博客
author:
  name:       Narsi
copyright:
  - Design by <a href="http://huangxc.com">Narsi</a>. Power by <a href="https://github.com/mojombo/jekyll" target="_blank">Jekyll</a> and <a href="https://github.com/" target="_blank">GitHub</a>. &copy; Copyright 2012

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
